version: "3.9"
services:

  # PHP service
  app:
    build: "./docker/php-fpm"
    container_name: php-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  # MySQL service
  db:
    build: "./docker/mariadb"
    ports:
      - "3306:3306"
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: php-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  devphpsocket:
    driver: local
  db:
    driver: local
